# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /~fsouto/mac0499/
exclude: 					[Gemfile, Gemfile.lock, script/]
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo


gems: 						[redcarpet, pygments.rb, jekyll-paginate, jekyll-gist]
paginate:         5
paginate_path: 		"page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde